### ISSUE TITLE
I can't find unifi clients

### ISSUE THREAD

**Issue by dkimmm** [xtreme22886/SmartThings_UniFi-Presence-Sensor#1]
Hello

I'm trying to find unifi clients but failed as attachment. 

Would you comment me wrong point? 

I have installed it on raspberry.

Thanks

![FullSizeRender](https://user-images.githubusercontent.com/48374451/84958197-cda9db00-b137-11ea-9ead-25d9a8ed5dda.jpeg)

**Comment by xtreme22886** [comment]
Hi @dkimmm,

Thanks for checking this out. First off, are you using a Unifi Dream Machine (UDM or UDMP)? This solution currently does not work for UDM devices.

If you are not using a UDM device, then the first check would be to see if the bridge (Raspberry Pi) has a valid config file.

Please browse to http://bridge-IP:9443/config. Can you tell me what you see when going to that URL? Please make sure to remove any sensitive data from your output.

Thanks

**Comment by dkimmm** [comment]
Hello @xtreme22886 

I'm using USG and AP pro. 

I can see this message. {"message":"Hello World"}  

Thanks

**Comment by xtreme22886** [comment]
Thanks @dkimmm, it should definitely work then.

The "Hello World" message shows when you don't specify an endpoint in the URL.

You entered http://bridge-IP:9443, you forgot the /config. Please let me know what you see when you add /config.

Thanks

**Comment by dkimmm** [comment]
Message as below. 

Should id and token same with something?

{"st":[{"app_url":"https://graph.api.smartthings.com:443/api/smartapps/installations/"},{"app_id":"**ID**"},{"access_token":"**TOKEN**"}],"unifi":[{"address":"10.0.1.39:8443"},{"username":"**NAME**"},{"password":"**PW**"},{"site":"default"}]}

**Comment by xtreme22886** [comment]
@dkimmm, no, for the most part, it all looks good. However, I see a missing setting for 'offline_delay'; which makes me think the raspberry pi docker image is not up to date...

Let me try on my end and see if I can reproduce the issue.

**Comment by dkimmm** [comment]
@xtreme22886 , Than Should I update docker and re-install?

**Comment by xtreme22886** [comment]
@dkimmm, I have just updated the docker image. Yes, please update docker image and reinstall. Please let me know how it goes.

**Comment by dkimmm** [comment]
@xtreme22886  It works well. Thank you for your help.
